# Generated by Django 5.2.10 on 2026-04-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_publication_year'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre'], name='main_book_genre_i_de9b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='main_book_publica_102aec_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre', 'publication_year'], name='main_book_genre_i_85ae2b_idx'),
        ),
    ]
